# Generated by Django 3.0 on 2020-10-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='phone',
            field=models.CharField(max_length=64),
        ),
    ]
