# Generated by Django 3.0 on 2020-10-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0002_auto_20201022_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_form',
            new_name='Contactform',
        ),
    ]
