# Generated by Django 3.0 on 2020-10-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0003_auto_20201022_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='fullname',
            field=models.CharField(default='dgdd', max_length=64),
        ),
    ]
