# Generated by Django 3.0 on 2020-10-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0004_auto_20201022_0856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productcategorie',
            new_name='stampcategory',
        ),
    ]
