# Generated by Django 3.0 on 2020-10-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0005_auto_20201022_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stampcategory',
            new_name='stamp',
        ),
    ]
