# Generated by Django 3.0 on 2020-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0007_auto_20201030_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsubscribbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
