# Generated by Django 3.0 on 2020-11-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0008_emailsubscribbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
