# Generated by Django 3.0 on 2020-12-05 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printapp.Category'),
        ),
    ]
