# Generated by Django 3.0 on 2020-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0011_stamp_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pricerange',
            field=models.CharField(default='Rs:', max_length=25),
        ),
        migrations.AddField(
            model_name='category',
            name='productimage',
            field=models.ImageField(default='', upload_to='productimage/'),
        ),
    ]
