# Generated by Django 3.0 on 2020-12-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0012_auto_20201205_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='productimage',
            field=models.ImageField(default='', upload_to='categoryproduct/'),
        ),
    ]
